language: node_js

node_js: "8.8.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - ./.travis.ci.sh

notifications:
  email:
    on_success: "never"
    on_failure: "never"
