default: &default
  secret_key_base: c01cb65c85729f6c294049205826a0408b91ec983446f308fc8bab4c5f62122d89d1c25460d4d789246e4e24bb45029c41c061f298ed2af7d9bf1e6db8f3cf8f
  vk_app_id: <%= ENV['VK_APP_ID'] %>
  vk_app_secret: <%= ENV['VK_APP_SECRET'] %>
  vk_redirect_uri: <%= ENV['VK_REDIRECT_URI'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
